#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty trash.

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias local-ip="ifconfig \
                    | grep 'inet addr' \
                    | grep -v '127.0.0.1' \
                    | cut -d: -f2 \
                    | cut -d' ' -f1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo apt-get update \
            && sudo apt-get upgrade \
            && npm install -g npm \
            && composer global update \
            && npm upgrade -g"
