#!/bin/bash

export LANG=en_US.UTF-8
source /usr/local/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git-flow-avh
antigen bundle zsh-autosuggestions
antigen bundle command-not-found
export NVM_LAZY=1
antigen bundle nvm
antigen bundle npm

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme
antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# Tell Antigen that you're done.
antigen apply

[ -n "$PS1" ] \
    && . ~/.bash_profile